# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

registries:
  # Configure OCT npm registry
  gh-pkgs:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{ secrets.VAULT_OPS_GITHUB_BUILD_TOKEN }}

updates:
  # 
  - package-ecosystem: npm
    directory: /
    registries:
      - gh-pkgs
    schedule:
      interval: daily
    groups:
      # Group for all prism related packages updates
      prism:
        patterns:
          - '@octanner/prism-*'

      # Group all dev dependencies
      dev-dependencies:
        dependency-type: development

      # Group all non-breaking changes
      minor-updates:
        update-types:
          - minor
          - patch
