
changelog:
  categories:
    - title: ✨ Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
    - title: DX
      labels:
        - dx
