name: Semantic Release

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Semantic Release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set the author name and email for the commit
          # GIT_AUTHOR_NAME: obertbot
          # GIT_AUTHOR_EMAIL: "<>"
          # GIT_COMMITTER_NAME: obertbot
          # GIT_COMMITTER_EMAIL: "<>"

        run: npm run release
