name: Semantic Release pkg

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  USER_NAME: github-actions[bot]
  USER_EMAIL: github-actions[bot]@users.noreply.github.com
jobs:
  release:
    env:
      # This is used to set the author and committer information for semantic release commits
      # If environment variables are not set, committer will be in the name of Semantic Release Bot instead of the GitHub Actions bot
      GIT_AUTHOR_NAME: "obertbot"
      GIT_AUTHOR_EMAIL: "obertbot@octanner.com"
      GIT_COMMITTER_NAME: "obertbot"
      GIT_COMMITTER_EMAIL: "obertbot@octanner.com"

    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20'

      # - name: Configure Git
      #   run: |
      #     git config user.name "${{ env.USER_NAME }}"
      #     git config user.email "${{ env.USER_EMAIL }}"

      - name: Configure Git
        run: |
          git config user.name ${{ env.GIT_AUTHOR_NAME }}
          git config user.email ${{ env.GIT_AUTHOR_EMAIL }}
        env:
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"


      - name: Setup .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      - name: Semantic Release Action
        uses: codfish/semantic-release-action@v3
        with:
          # Define the list of plugins to use. Plugins will run in series, in the order defined, for each steps if they implement it. https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#plugins
          additional-packages: |
            ['conventional-changelog-conventionalcommits@6', '@semantic-release/changelog', '@semantic-release/git']
        env:
          # Used for publishing to package and Github release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




# # Run Semantic Release
# - name: Run Semantic Release
#   env:
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     # Set the author name and email for the commit

#     GIT_AUTHOR_NAME: ${{ env.USER_NAME }}
#     GIT_AUTHOR_EMAIL: ${{ env.USER_EMAIL }}
#     # GIT_COMMITTER_NAME: ${{ env.USER_NAME }}
#     # GIT_COMMITTER_EMAIL: ${{ env.USER_EMAIL }}

#     # NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   run: npm run release

# - name: Release
#   run: npm run release
#   env:
#     # Used for publishing to package and Github release
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     GIT_AUTHOR_NAME: ${{ env.USER_NAME }}
#     GIT_AUTHOR_EMAIL: ${{ env.USER_EMAIL }}
